name: fiducia_flutter
description: Formally specified Fiducia mobile and cross-platform desktop client.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  app_links: ^7.2.1
  cupertino_icons: ^1.0.8
  fiducia_interfaces:
    git:
      url: https://github.com/fiducia-cloud/fiducia-interfaces.git
      ref: fbc1c5b308d63c3aece62ca09fa4a8f56fb62c5f
      path: generated/dart
  flutter:
    sdk: flutter
  http: ^1.5.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
